name:                math190-site
version:             0.1.0.0
github:              "gmcninch-tufts/2024-Sp-Math190"
license:             BSD3
author:              "George McNinch"
maintainer:          "george.mcninch@tufts.edu"
copyright:           "2024 George McNinch"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/gmcninch/personal#readme>

dependencies:
- base >= 4.7 && < 5
- hakyll
- pandoc

executables:
  math190-site:
    main:                site.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
